# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-12 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_foodtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
