# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-12 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_delete_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
