# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-12 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20200212_1152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table='axf_foodtype',
        ),
    ]
